version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: todo-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - todo-network
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - todo-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
